/*mod eduni_errata2e_error;
mod eduni_errata2e_invalid;
mod eduni_errata2e_notwf;
mod eduni_errata2e_valid;
mod eduni_errata3e_invalid;
mod eduni_errata3e_notwf;
mod eduni_errata3e_valid;
mod eduni_errata4e_error;
mod eduni_errata4e_invalid;
mod eduni_errata4e_notwf;
mod eduni_errata4e_valid;
mod eduni_misc_invalid;
mod eduni_misc_notwf;*/
/*mod eduni_namespaces_10_error;
mod eduni_namespaces_10_invalid;
mod eduni_namespaces_10_notwf;
mod eduni_namespaces_10_valid;
mod eduni_namespaces_11_notwf;
mod eduni_namespaces_11_valid;
mod eduni_namespaces_errata1e_notwf;
mod eduni_xml11_error;
mod eduni_xml11_invalid;
mod eduni_xml11_notwf;
mod eduni_xml11_valid;
mod ibm11_invalid;
mod ibm11_notwf;
mod ibm11_valid;
mod ibm_error;
mod ibm_invalid;
mod ibm_notwf;
mod ibm_valid;
mod oasis_error;
mod oasis_invalid;
mod oasis_notwf;
mod oasis_valid;
mod sun_error;
mod sun_invalid;*/
mod sun_notwf;
/* not yet checked
mod sun_valid;
mod xmltest_invalid;
mod xmltest_notwf_ext_sa;
mod xmltest_notwf_not_sa;
mod xmltest_notwf_sa;
mod xmltest_valid_ext_sa;
mod xmltest_valid_not_sa;
mod xmltest_valid_sa;
mod xmltest_valid_sa_canonicalonly;
*/
